# -*- coding: utf-8 -*-
"""DataStructure240126.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaBV0ZKzjn8E_vx4Fe4ULa3BpM0FXbY9
"""

# Data Structures In Python
# A data structure is a way of organizing and storing data so it can be used efficiently.

# Why We Need Them
# They organize data in a structured way.
# They help store data efficiently.
# They make it easy to access and use data.
# They allow data to be managed easily, such as adding, removing, or searching.

# LIST TUPLE SET DICTIONARY

# LIST IN PYTHON
# LIST IS A DATA STRUCTURE USED TO STORE COLLECTION OF DATA VALUES
# LIST IS AN ITERABLE IN PYTHON
# LIST IS AN ORDERED COLLECTION OF DATA VALUES
# LIST IS MUTABLE IN NATURE [remove , add , delete , modify , update]
# IN LIST WE CAN STORE MIXED DATA TYPE
# IN PYTHON LIST CAN BE DEFINED BY USING [] OR list()
# IN LIST WE CAN STORE DUPLICATE ELEMENTS

# CREATE A LIST

list1 = [10,20,30,40,50,60]
print(type(list1))

list2 = ['a,b,c']
print(type(list2))

list3 = []
print(type(list3))

# Indexing and slicing

list1 = [10,20,30,40,50,60]

# 10 20 30 40 50 60
# 0   1  2  3  4  5
#-6  -5  -4 -3 -2 -1

print(list1)
print(list1[3])
print(list1[-1])
print(list1[1:5])
print(list1[1:5:2])
print(list1[::-1])

# LIST IS AN ITERABLE IN PYTHON

# using 'for' loops

list1 = [10,20,30,40,50,60]

for i in list1:
  print(i)

# using for loop , print list element along with their index number


# len(iterable/sequence)
# used to return the number of elements in a Sequence

# example 1

list1 = [10,20,30,40,50,60]

print(len(list1))

# Example 2

   # Index 0 : list1[0]

#example 3

# using index () method
# index () used to to return index number of specified value

list1 = [10,20,30,40,50,60]
print(list1.index(30))

# example 4

list1 = [10,20,30,40,50,60]
for i in list1:
  print(f"index {list1.index(i)} : {i}")

# enumerate()----> menyenaraikan 1 persatu sambil memberikan no index
# its a built in function use to return element with index number

list1 = [10,20,30,40,50,60]
for i in enumerate(list1):
  print(i)

# enumerate ---> use this 1

for i,s in enumerate(list1):    # {i}-->will iterate IndexNo  #e--> will iterate Elements
  print(f"index {i} : {s}")     # {s} is just avariable name, can give any name to it

# IN LIST WE CAN STORE MIXED DATA TYPE

stInfo = [123 , "John" , 32 , "Python" , 78.21 , True , True , True]
print(stInfo)

# LIST BUILT-IN METHODS

mylist = [10,20,30,40,50,60,70,80,90,100]
print('Original List :',mylist)

# a.) append(value)
# used to add a new element at the END of the List

mylist.append(110)
print('After Append :',mylist)

# b.) insert(indexNumber,value)
# used to add a new element at any Specific position in List

mylist.insert(4,400) # 4 is index number
print('After Insert :',mylist)

# c.) pop(indexNumber) ##--> DELETION
# used to delete an element from the specified index number

mylist.pop(4)
print('After Pop :',mylist)

# d.) pop()
# used to delete the Last element from List

mylist.pop()
print('After Pop :',mylist)

# e.) remove(value)
# used to remove the specified element from a List

mylist.remove(80)
print('After Remove:',mylist)

# Commonly ASK interview question *****
# if we try to delete an element which does not exist it will give an Error
# list = [10,20,30,40,10,10,10,50,60,70]
# list.remove(10)
# it will delete the First Occurence of the Specified value
# if want to remove multiple number (10) need to use loops



# f.) reverse()
# used to print the list in a reverse order

mylist.reverse()
print('After Reverse:',mylist)

# g.) clear()
# used to remove all elements from the List

mylist.clear()
print('After Clear:',mylist)

# h.) del keyword -- will remove your entire list

del mylist

# i.) sort()

# example 1
price = [56,20,12,90,87,45,32,18,10,37,29]
price.sort() # by default it will in ascending order
print(price)

# example 2

price = [56,20,12,90,87,45,32,18,10,37,29]
price.sort(reverse=True) # descending order
print(price)

# remove all the 10 from the list

list1 = [10,20,10,30,40,10,10,50,60,10]
while 10 in list1:
  list1.remove(10)
print(list1)

# Task 1
# list1 = [10,20,10,30,40,10,10,50,60,10]
# keep the second 10 only
# list1 = [20,10,30,40,50,60]

list1 = [10,20,10,30,40,10,10,50,60,10]

count = 0
result = []

for item in list1:
    if item == 10:
        count += 1
        if count == 2:
            continue   # skip 10 yang kedua sahaja
    result.append(item)

print(result)


# Task 2
# list1 = [10,20,10,30,40,10,10,50,60,10]
# just delete second 10 only
# list1 = [10,20,30,40,10,10,50,60,10]

#*************************************************
# TUPLE IN PYTHON
# TUPLE IS A DATA STRUCTURE USED TO STORE COLLECTION OF DATA VALUES
# TUPLE IS AN ITERABLE IN PYTHON
# TUPLE IS AN ORDERED COLLECTION OF DATA VALUES
# TUPLE IS IMMUTABLE IN NATURE         (tak boleh di ubah)
# IN TUPLE WE CAN STORE MIXED DATA TYPE
# IN PYTHON TUPLE CAN BE DEFINED BY USING () OR tuple()
# IN TUPLE WE CAN STORE DUPLICATE ELEMENTS

# CREATE A TUPLE

tupl1 = (10,20,30,40,50,60)
print(type(tupl1))

tupl2 = tuple((10,20,30,40,50,60))
print(type(tupl2))

tupl3 = ()
print(type(tupl3))

myvar = 10 , "John" , 90.21 , True , [10,20,30]
print(type(myvar))

# How to create a tuple having one element

tupl1 = (10,)
print(type(tupl1))
print(tupl1[0])

# Tuple Is Immutable

tupl = (10,20,30,40,50)
print(tupl)

tupl[2] = 300
print(tupl)

tupl = (10,20,30,40,10,10,50,60,10,10,70,80)
# len()
print('No. Of Elements :',len(tupl))
# count(value) --> it will count the occurence of specified value
print('No. Of Times 10 Appears :',tupl.count(10))
# index(value) --> it will get the index number of specified value
print('Index No. of 70 :',tupl.index(70))

tupl = (10,20,30,40,10,10,50,60,10,10,70,80)
# sorted() function works on any iterable
# returns a new list of sorted elements
print(sorted(tupl))
print(sorted(tupl,reverse=True))

# SET IN PYTHON
# SET IS A DATA STRUCTURE USED TO STORE COLLECTION OF DATA VALUES
# SET IS AN ITERABLE IN PYTHON
# SET IS AN UN-ORDERED COLLECTION OF DATA VALUES
# IN PYTHON SET CAN BE DEFINED BY USING {} OR set()
# IN SET WE CANNOT STORE DUPLICATE ELEMENTS

# CREATE A SET

set1 = {10,20,30,40}
print(type(set1))

set2 = set({10,20,30,40})
print(type(set2))

set3 = set()
print(type(set3))

list1 = [10,20,30,40,50,60]
print(list1)

t1 = (10,20,30,40,50,60)
print(t1)

set1 = {10,20,30,40,50,60} # set is an unordered collection of data elements
print(set1)

mylist = [10,20,10,30,30,40,50,60,40,10,10,30,60]
# how many no. of unique elements we have in a list

# install ordered-set
# An OrderedSet is a mutable data structure that is a hybrid of a list and a set.
# It remembers the order of its entries, and every entry has an index number
# that can be looked up.
# https://pypi.org/project/ordered-set/
# pip --> python installer package

!pip install ordered-set

from ordered_set import OrderedSet

# Guess a number game
# your machine will generate a random number
# we need to guess that number in 4 attempts

import random
guessAttempt = 1
print('Guess A Number Game 🤖')
print('Enter Your Name')
name = input()
print(f'Welcome User {name} 😎')
print('I am generating one random number between 1 till 13 👻 Please Wait.....')
num = random.randint(1,13)
print('✅ Number Is Generated. Guess The Number in 4 Attempts')

while guessAttempt <= 4:
  print(f'\n{guessAttempt} Attempt. Enter Your Guess.')
  user_guess = int(input())

  if user_guess == num:
    print(f'Congratulation 🤩 You Guess The Number Right In {guessAttempt} Attempt.')
    break

  if user_guess > num:
    print('⬆️ Your Guess Is Too High. Think Of A Lower Number\n')

  if user_guess < num:
    print('⬇️ Your Guess Is Too Low. Think Of A Higher Number\n')

  guessAttempt = guessAttempt + 1

if user_guess != num:
  print('🛑 Zero Attempt Left. Game Over ! ')
  print(f'The Correct Number Was 📢 {num}')

# DICTIONARY ***************************************************************
# USED TO STORE INFORMATION IN A KEY:VALUE PAIR FORMAT
# DICTIONARY IS DEFINED BY USING {} or dict()
# DICTIONARY IS MUTABLE IN NATURE
# IN DICTIONARY KEY HAS TO BE UNIQUE , BUT VALUES CAN BE DUPLICATED


#            key:value
emp_info = {"id":123 , "name":"john" , "dept":"it" , "age":32 , "salary":8900 , "email":"j@gmail.com" , "city":"klang"}

print(type(emp_info))
print(emp_info)
print(emp_info['name'])
print(emp_info["email"])

# 'get' (KeyName)

print(emp_info.get("email"))

# Add new key:value pair
# dictionary will add new key:value pair at the END

emp_info["country"] = "England"
print(emp_info)

# Updating the value

emp_info["age"] = 55
print(emp_info)

emp_info["country"] = "malaysia"
print(emp_info)

# DELETE** key:value pair
# pop(keyname)

emp_info.pop("country")
print(emp_info)

# updating the key

emp_info["department"] = emp_info.pop("dept") # first return the value and delete this key
print(emp_info)                               # will appear at the END of the dictionary

mydict = {2:4 , 3:9 , 4:16 , 5.0:25}
print(mydict)

emp_details = {"id": [101,102,103] , 'name' : ['john','james','wan'] , 'dept' : ['hr','it','fn']}

print(emp_details)
print(emp_details['name'])
print(emp_details['name'][2])

import pandas as pd
df = pd.DataFrame(emp_details)
df

emp_info = {"id":123 , "name":"john" , "dept":"it" , "age":32 , "salary":8900 , "email":"j@gmail.com" , "city":"klang"}

# normal 'for' loop will print only keys
for i in emp_info:
  print(i)

# to print values
for i in emp_info.values():
  print(i)

# to print keys and value together
for k,v in emp_info.items(): # k=keys v=values
  print(f'{k} : {v}')

# task
# taking subject marks from a faculty

# ask how many marks faculty wish to insert
# insert marks1
# insert marks2
# insert marks3
# save this marks --> list

# inserted marks are
# marks 1 :
# marks 2 :
# marks 3 :



total_marks = int(input('How many marks faculty wish to insert : '))
marks_list = []

for i in range(total_marks):
  mark = int(input(" insert Marks " + str(i + 1) + ": "))
  marks_list.append(mark)

print("Inserted marks are:")
for i in range(len(marks_list)):
    print("Mark", i + 1, ":", marks_list[i])

#################CHATGPT SOLUTION

# ask how many marks the faculty wants to insert
total_marks = int(input("How many marks do you want to insert? "))

# create an empty list to store marks
marks_list = []

# take marks one by one
for i in range(total_marks):
    mark = int(input("Enter mark: "))
    marks_list.append(mark)

# display the marks
print("Inserted marks are:")
for i in range(len(marks_list)):
    print("Mark", i + 1, ":", marks_list[i])

# YASH SOLUTION
howManyMarks = int(input('Enter How Many Marks You Wish To Insert : '))
i = 1
marksList = []

while i <= howManyMarks:
  marks = int(input(f'Enter Marks {i} : '))
  marksList.append(marks)
  i += 1

print('\nInserted Marks Are : ')
for x in range(len(marksList)):
  print(f'Marks {x+1} : {marksList[x]}')