# -*- coding: utf-8 -*-
"""Loops20126.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsulRzMfmGSfY0TMZ4l9j0Hqqu6MYJ1V
"""

# Loops

#1. Loops in Python are used to repeat a block of code multiple times without
# writing the same code again and again.

#2. Loops help us repeat tasks efficiently and smartly.

#3. A loop is a control structure that repeats a block of code until a condition is met.

#4. in python loops is divided into 2 categories 'for' and 'while'

#***********************************************
# 'for' loop
# it is used to iterate over a Sequence [string , list , tuple , array etc...]

# 'Iterate over a sequence' bermaksud proses mengakses atau memproses setiap
# elemen dalam satu susunan data secara satu per satu, biasanya mengikut turutan

# 'for' iterable_variable in Sequence: code to be executed

# AFTER EVERY ITERATION BODY OF FOR LOOP WILL BE EXECUTED

# example 1
for i in "Python":
  print(i)

# example 2
for cup in "bungkus":
  print(cup)

# write a program (WAP) to print python 10x

# EXAMPLE 1 (not valid approach)
print("python\n"*5)

product_prices = 12,15,17,18,21,23,25,28,30,32,35,38,39,40,43,45,48,50,53,54
tax = 1.08


# Example 1 using index
print(product_prices[0]+tax)
print(product_prices[1]+tax)
print(product_prices[2]+tax)
print(product_prices[3]+tax)
print(product_prices[4]+tax)
print(product_prices[5]+tax)

# example 2 using 'for' loops

product_prices = 12,15,17,18,21,23,25,28,30,32,35,38,39,40,43,45,48,50,53,54,55,57,58
tax = 1.08

for price in product_prices:
  print(price-tax)

# print all even numbers only

numbers = 12,15,17,18,21,23,25,28,30,32,35,38,39,40,43,45,48,50,53,54,55,57,58

for n in numbers:  # use 'if' in decision making
  if n%2 == 1:     # n(divided)2 == 0:
    print(n)

# Task - print those names starts with letter 'a' or 'A'

emp_names = ['alex','smith','john','Alijah','ariah','mathews','amir','jamison','Aisyah']

for name in emp_names:  #loops
  if name.startswith('a') or name.startswith('A'): ## if used to check the condition first
    print(name)     # if the condition is TRUE it will execute the block of code

# range() function
# it is used to generate a sequence of integer values (numbers)

# range(x)
# it is used to generate a sequence of integer values (numbers)
# starting from Zero till x-1 - if 10 it will show 0-9 (10 numbers but starts at 0)


# EXAMPLE 1

print(list(range(11)))

# range(x,y)
# it is used to generate a sequence of integer values(numbers)
# starting from x till y-1 - if 11 it will show 1-10 (starts at 1)

print(list(range(1,11)))

# range(x,y,stepCount)
# it is used to generate a sequence of integer values(numbers)
# starting from x till y-1 based on stepCount

print(list(range(1,11,2)))

# task - using range function , print all even numbers till 100
print(list(range(0,101,2)))

# EXAMPLE 2 write a program to print python 10x
# this is how range is connected to loops

for i in range(1,11):
  print(f"{i}.Python")

# write a program - print a mathematical

num = int(input("enter any number : "))

for i in range(1,13):
  print(f"{num} x {i} = {num*i}")

# Nested For Loop
# for loop defined inside another for loop

# EXAMPLE 1
colors = ["red","blue","green"] # inner loop
vehicles = ['car',"bike",'bus'] # outer loop

# outer loop will wait untill inner loop finishes the iteration

for c in colors:
  for v in vehicles:
    print(c,v)

# EXAMPLE 2


rows = 5
for i in range(1,rows+1):
  for j in range(i):
    print('*',end=" ")
  print()

"""https://www.wscubetech.com/resources/python/programs/star-pattern

# to practice to print star pattern in Loops
"""



#********************

#1. 'while' loop
#2. 'while' loop repeats a block of code
# until a certain condition met

# syntax

# initialization
# 'while' condition:
#  a block of code
#  increment / decrement

#1. 'While' checks the condition first
#2. if the condition is TRUE 'while' will execute the block of code
#3. after executing the block of code 'while' will check the condition again


i = 1
while i<=5:    # 1<=3 (t)           2<=3(t)             3<=3(t)         4<=3(F)
  print(i)     # 1                  2                   3
  i += 1       # i = 1 + 1 (2)      i = 2 + 1 (3)       i = 3 + 1 (4)

# print mathemetical table of a number using 'while' loop

num = int(input('Enter Any Number : '))
i = 1
while i<=10:
  print(f"{num} x {i} = {num*i}")
  i += 1

# Use 'while' loop when the number of iteration is not known

# Palindrome of a Number

# Example of Palindrome Number
#   1331  121 66766

# How to kow a palindrome Number
#1. Divide the number by 10 and get its remainder
#2. save that number by multiplying it with 10
#3. update the number by dividing the number by 10
#     repeat these step until number become zero

# Example 1
num = 121       #number
temp = num      #temporary
sum = 0         #sums

while num!=0:         #1st iteration 121/10
  rem = num % 10      # rem = 1
  sum = sum*10 + rem  # sum = 1 (0*10 + rem)
  num = num // 10     # num = 12

if temp == sum:
  print('Palindrome Number')

else:
  print('Not A Palindrome Number')

print(1570%12)
print(9%1570)

# task

num = 12345
temp = num
sum = 0

while num!=0:
  rem = num % 10
  sum = sum*10 + rem
  num = num // 10

if temp == sum:
  print('palindrome number')

else:
  print('not a palindrome number')

num = 121
temp = num   # temp is dummy variable
sum = 0

while num!=0:           # 1st Iteration   2nd Iteration   3rd Iteration   4th Iteration   5th Iteration
  rem = num % 10        # rem = 5         rem = 4         rem = 3         rem = 2         rem = 1
  sum = sum*10 + rem    # sum = 5         sum = 54        sum = 543       sum = 5432      sum = 54321
  num = num // 10       # num = 1234      num = 123       num = 12        num = 1         num = 0

print(num,sum)
if temp == sum:
  print('Palindrome Number')
else:
  print('Not Palindrome Number')

num = 12345
temp = num  # here we have the copy of original number
sum = 0

while num>0:           # 12345>0   (t)        1234>0 (t)     123>0 (t)    12>0          1>0           0>0 (f)
  rem = num % 10       # rem = 5              rem =  4       rem = 3      rem = 2       rem = 1
  sum = sum*10 + rem   # sum = 5              sum =  54      sum = 543    sum = 5432    sum = 54321
  num = num // 10      # num = 1234           num = 123      num = 12     num = 1       num = 0

if temp == sum:  # 12345 == 54321
  print('Palindrome Number')
else:
  print('Not A Palindrome')

# python smart app ask by user

# avoiding infinite loop
# i = 1
# while i<=3
# print(i)

while true:
  user_input = ('ask any question. Type exit or quit to stop')
  if user_input == 'exit' or user_input == 'quit':
    break

# Break and continue statement

# Break statement *
#1. it is use to terminate the execution of a LOOP
#2. break and continue should be defined in inside decision making


# example 1 break

for i in range(1,11):
  if i == 5:
    break
  print(i)


#example 2 continue

for i in range(1,11):
  if i == 5 or i == 9:
    continue
  print(i)