# -*- coding: utf-8 -*-
"""Pandas_020426.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeA0cdbrnbTGPfb1FRZEuT325y5Y449G
"""

import pandas as pd
import numpy as np

# https://www.mockaroo.com/     ---> to generate dummy random data set for practice

# https://pandas.pydata.org/docs/user_guide/io.html

# Excel File

# https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx
# https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv
# https://raw.githubusercontent.com/prefuse/Prefuse/refs/heads/master/data/fisher.iris.txt
# https://raw.githubusercontent.com/yash240990/Python/master/simple.json

# Pandas
# Pandas is a powerful and flexible Python package that allows you to work with labeled and
# time series data. It also provides statistics methods, enables plotting, and more.
# One crucial feature of pandas is its ability to write and read Excel, CSV, and many other types of files.

# Reading An Excel File
# Reading A CSV File
# Reading tab-delimited file
# Reading A JSON File
# Uploading Local Files In Google Colab

# Reading An Excel File
# read_excel()

dt = pd.read_excel('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
dt

type(data)

# Reading The Data From A Different Sheet
# Load The Entire Excel Workbook

excelFile = pd.ExcelFile('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
excelFile.sheet_names
# use this to check for sheet names

# Reading The Data From A Different Sheet
# Load The Entire Excel Workbook


data = pd.read_excel(excelFile,'Sheet2')
data
# use this to read the selected sheet

# Reading a CSV File
# Comma Seperated Value (CSV)

data = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv')
data

# Reading tab-delimited file
# Reading the content of Excel file saved with .txt format

data = pd.read_csv('https://raw.githubusercontent.com/prefuse/Prefuse/refs/heads/master/data/fisher.iris.txt',)
data

# still not readable



# use additional ,sep='\t' to a more readable format

data = pd.read_csv('https://raw.githubusercontent.com/prefuse/Prefuse/refs/heads/master/data/fisher.iris.txt',sep='\t')
data

from google.colab import files
# Reading a JSON file (Java Script Object and Notation)

data = pd.read_json('https://raw.githubusercontent.com/yash240990/Python/master/simple.json')
data

# Uploading Local Files In Google Colab

from google.colab import files
uploaded = files.upload()         # file upload wizard

!ls  # List The Files ---> check for the uploaded file

# Check the uploaded Excel file

dt = pd.read_excel('MOCK_DATA.xlsx')
dt